version: "3.3"

services:

  cappa-antiplag:
    build:
      context: ..
      args:
        - SANDBOX_USER_UID=999
        - SANDBOX_DIR=/sandbox
      dockerfile: ./docker/Dockerfile
    container_name: cappa-antiplag
    image: cappa-antiplag
    volumes:
      - ../src:/app/src
      - docker_shared_files:/files:ro
    ports:
      - "8000:8000"
    networks:
      - docker_localhost
    environment:
      - SANDBOX_USER_UID=999
      - SANDBOX_DIR=/sandbox
    restart: on-failure
    command: gunicorn --pythonpath '/app/src' --bind 0:8000 app.main:app --reload -w 1

networks:
  docker_localhost:
    external: true

volumes:
  docker_shared_files:
    external: true