version: "3.3"

services:

  cappa-antiplag:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: cappa-antiplag
    image: cappa-antiplag
    volumes:
      - ../src:/app/src
    ports:
      - "8001:8001"
    environment:
      - SANDBOX_USER_UID=999
      - SANDBOX_DIR=/sandbox
    restart: on-failure
    command: gunicorn --pythonpath '/app/src' --bind 0:8001 app.main:app --reload -w 1
