version: "3.3"

services:

  antiplag:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: antiplag
    image: antiplag
    volumes:
      - ../src:/app/src
    networks:
      - localhost
    ports:
      - "9020:9020"
    restart: on-failure
    command: >
      gunicorn app.main:app
      --bind 0.0.0.0:9020
      --workers 1
      --worker-class uvicorn.workers.UvicornWorker
      --log-level debug
      --timeout 60
      --reload
networks:
  localhost:
    external: true
