version: "3.3"

services:

  antiplag:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: antiplag
    image: antiplag
    volumes:
      - ../src:/app/src
    networks:
      - localhost
    ports:
      - "9020:9020"
    restart: on-failure
    command: uvicorn app.main:app --host 0.0.0.0 --port 9020 --reload --workers 1

networks:
  localhost:
    external: true
