version: "3.3"

services:

  antiplag:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: antiplag
    image: antiplag
    volumes:
      - ../src:/app/src
    networks:
      - localhost
    ports:
      - "9020:9020"
    restart: on-failure
    command: gunicorn --pythonpath '/app/src' --bind 0:9020 app.main:app --reload -w 1

networks:
  localhost:
    external: true
